version: '3'
services:
  postgres:
    image: 'postgres:latest'
  gnarly:
    restart: on-failure
    depends_on:
      - postgres
    image: 'shrugs/gnarly-test:demo'
    environment:
      DEBUG: '*,-sequelize*,-gnarly-core:store:*,-gnarly-core:api,-gnarly-core:blockstream:fast-forward'
      NODE_ENDPOINT: 'https://mainnet.infura.io'
      CONNECTION_STRING: 'postgres://postgres@postgres:5432/postgres'
      GNARLY_RESET: 'true'
  paperboy:
    depends_on:
      - gnarly
    image: 'shrugs/paperboy:demo'
    environment:
      DEBUG: 'paperboy*'
      GNARLY_DATABASE_URL: 'postgres://postgres@postgres:5432/postgres'
      PORT: '3000'
    ports:
      - '3000:3000'
